/*
LifePlus Healthcare Platform API

Testing PackageOrdersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lifeplusapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/LifeplusBangladesh/lifeplus-go-sdk"
)

func Test_lifeplusapi_PackageOrdersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PackageOrdersAPIService PackageOrdersCorporateEnrollmentPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.PackageOrdersAPI.PackageOrdersCorporateEnrollmentPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PackageOrdersAPIService PackageOrdersIdClaimsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		httpRes, err := apiClient.PackageOrdersAPI.PackageOrdersIdClaimsPost(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PackageOrdersAPIService PackageOrdersIdServiceUsagePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		httpRes, err := apiClient.PackageOrdersAPI.PackageOrdersIdServiceUsagePost(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
